---
- name: Install HAProxy package
  become: true
  ansible.builtin.package:
    name: haproxy
    state: latest

- name: Deploy HAProxy configuration
  become: true
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify:
    - Restart HAProxy

- name: Enable and start HAProxy service
  become: true
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    state: started
