---
wireguard_iface: wg1
listen_port: 51820               # Local listen port for WireGuard interface
persistent_keepalive: 25         # Persistent keepalive interval (seconds) to maintain NAT mappings
